sudo: false
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
script:
  - coverage run --source xmlserdes -m py.test --doctest-modules tests
after_success:
  - coveralls
